If I include output of getStats to the error notification, I receive the following info:
This seems to be an option of pylibmc, which is a python wrapper around the libmemcached, but the docs says, that this option belongs to the ones directly configurable in libmemcached.
The are only checked at the time a connection to the server has to be made.
Somehow the code preparing the configuration string for use was messed up, and a space character went in front of one of the memcache server names.
When memcached write fails, I receive an email notification.
This message would be issued when a connection exceeds time-out and/or retry limit.
In my case the reason for this error message was an incorrect server name.
In my case turning off the behavior option tcp_nodelay made it work.
About once per day "SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY" error comes and I have no idea how to find the reason.
Naturally, as this is a temporary issue, you would architect your PHP application to fall-over to the next cache server, or pull affected server out of server list.
I'm unable to confirm how pecl_memcached handles this error, but I imagine it would be treated as a standard connectivity error.
MEMCACHED_SERVER_TEMPORARILY_DISABLED or "SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY" is generated by libmemcached library.
I tried adding -v flag, but it does not help, the log remains empty.
Adding the server name with the space worked without any complaint, i.e.
This results in the above mentioned error message when reading from the server.
For more info see pylibmc docs http://sendapatch.se/projects/pylibmc/behaviors.html